#! /bin/sh

## Autostart ##
polybar &
kitty &
picom &
feh --bg-scale ~/.dotfiles/wallpapers/wallpaper7.jpg
setxkbmap -layout es 
pgrep -x sxhkd > /dev/null || sxhkd &

## Workspaces ##
bspc monitor -d 1 2 3 4 5 6

bspc config merge_overlapping_monitors true

# Padding config
bspc config top_padding 25

# Border config
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config focused_border_color "#8fbcbb"
bscp config normal_border_color "#00FFFFFF"


# Split config
bspc config window_gap 15
bspc config split_ratio 0.55


## Rules ##
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
